name: Build and Push Docker Image to ECR

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  AWS_REGION:  ${{ secrets.AWS_REGION }}
  ECR_REGISTRY:  ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY:  ${{ secrets.ECR_REPOSITORY }}

jobs:
  build-and-push:
    name: Package and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch:depth: 0

      - name: Debug secrets (safely for debug only)
        run: |
          echo "ECR Registry: ${REG}X"
          echo "ECR Repo: ${REPO}X"
          echo "Full tag: ${REG}/${REPO}:${GITHUB_SHA}X"
        env:
          REG: ${{ secrets.ECR_REGISTRY }}
          REPO: ${{ secrets.ECR_REPOSITORY }}
          GITHUB_SHA: ${{ github.sha }}


      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          overwrite-settings: false
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Debug Docker tag
        run:
          echo "Debug Docker tag-  ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"


      - name: Build, tag, and push image to ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Print pushed image URL
        run: echo "✅ Image pushed to  ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
